#!/usr/bin/env bash
# This Script configures error 404 a new Ubuntu machine

# Updateting packages before installations
sudo apt-get update
sudo apt-get install -y nginx

# creates index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# permanent redirection (301)
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# This script code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Test configuration for syntax errors
sudo nginx -t

# Restart nginx after making changes
sudo service nginx restart
