#!/usr/bin/env bash
# This  is the script that generates MySQL dump and creates a compressed archive...

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
