#!/usr/bin/env bash
# In this script we:
# Create the file /var/run/myscript.pid containing its PID
# Display To infinity and beyond indefinitely
# Display I hate the kill command when receiving a SIGTERM signal
# Display Y U no love me?! when receiving a SIGINT signal
# Delete the file /var/run/myscript.pid and terminates itself when it
# receives a SIGQUIT or SIGTERM signal


echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do 
    echo 'To infinity and beyond' 
    sleep 2
done
