#!/usr/bin/env bash
# Script that displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

quifile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$quifile"
