#!/usr/bin/env bash
# This script parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

quifile="apache-access.log"
awk -F' ' '{ print $1, $9}' $quifile | sort | uniq -c|sort -nr
