#!/usr/bin/env bash
# Script that loops through 1 to 10 using while loop

z=1

while [ $z -le 10 ]
do
    if [ $z -eq 4 ]
    then
        echo "bad luck"
    elif [ $z -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((z++))
done
