#!/usr/bin/env bash
# script that displays the content of the current directory in list format
# Only displays the part of the name after the first dash

quilist=$(ls)

for z in $quilist; do
  echo "$z" | cut -d '-' -f2
done
