#!/usr/bin/env bash
# script that displays the content of the current directory in list format
# Only displays the part of the name after the first dash

mylist=$(ls)

for z in $mylist; do
  echo "$z" | cut -d '-' -f2
done
